[project]
name = "astrouda"
version = "0.1.0"
requires-python = ">=3.12"
description = ""
authors =[
    {name="voetberg", email="maggiev@fnal.gov"}

]
readme = "README.md"

dependencies = [
    "click>=8.1.7",
    "matplotlib>=3.10.3",
    "numpy>=2.2.6", 
    "torch>=2.11.0", 
    "h5py>=3.16.0"

]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["astrouda"]

[project.scripts]
astrouda = "astrouda.run:main"